name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Download Ncnn libs
      run: |
        wget https://github.com/Tencent/ncnn/releases/download/20221128/ncnn-20221128-android-vulkan.zip
        unzip ./ncnn-20221128-android-vulkan.zip
        cp -r -f ./ncnn-20221128-android-vulkan ./app/src/main/cpp/ncnn

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Zip .so outputs
      uses: actions/upload-artifact@v3.1.2
      with:
        name: vits_android_libs
        path: app/build/intermediates/stripped_native_libs/release/out/lib
